@startuml
'https://plantuml.com/sequence-diagram

class ToDoListController {
    - TextArea display
    - TextArea dueDateError
    - TextArea dueDateError2
    - TextField filePathForList
    - TextField newItemDescription
    - TextField newItemDueDate
    - TextField itemNumber
    - TextField editItemDescription
    - TextField editItemDueDate
    - TextField removeItemGiven
    - TextField itemDueDate
    + List<ToDo_List> lists
    + void addItemGateway()
    + void addItem(String description, String dueDate)
    + void removeItemGateway()
    + void removeItem()
    + void clearItems()
    + void displayAllItems()
    + void displayCompletedItems()
    + void displayIncompleteItems()
    + void saveList()
    + void loadGateway()
    + void loadList(String filePath)
    + void markCompleteGateway()
    + void markComplete(int itemNum)
    + void editDescriptionGateway()
    + void editDescription(int itemNum, String newDescription)
    + void editDueDateGateway()
    + void editDueDate(int itemNum, String newDueDate)
}
class Item {
    # String description
    # String dueDate
    # boolean completed
    + String getDescription()
    + String getDueDate()
    + boolean isCompleted()
    + void setDescription(String newDescription)
    + void setDueDate(String newDueDate)
    + void setIncomplete()
    + void setComplete()
}

ToDoListController <|---Item
@enduml